### ISSUE TITLE
Ai2svelte component accessibility fixes

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/graphics-svelte-components#26]
For discussion about improving the Ai2svelte component to make it work better for screen readers. Please leave comments if you have suggestions or thoughts. Thanks!

## Problem
The html text in ai2svelte is usually unintelligible and unhelpful for screen readers.
## Goal
Hide the text in ai2svelte from screen readers by default using `aria-hidden='true'` and make it easy for us to add AltText that better describes the graphic. Make it so we can turn off this feature in case we do want the text in ai2svelte to be read aloud.

### In the Ai2svelte component:
- Wrap ai2svelte component in `<div class="ai-wrapper" aria-hidden="{ariaHidden}"></div>`, which hides it from screen readers by default
- Add `ariaHidden` variable which defaults to true but can be set to "false" in the google doc
- Add ` <slot name="srDescription" /> ` which pulls the AltText for screen readers from google doc

*[See PR here](https://github.com/reuters-graphics/graphics-svelte-components/pull/24)*

### In bluprint_graphics-kit:
- Add `srDescription` slot in Page.svelte when Ai2svelte.svelte is being called. This description is made invisible on the page with CSS that applies to `sr-only` class
- Bootstrap has a built-in CSS for `.sr-only` that makes text invisible on the page but is read aloud in screen readers. Hard-code and add this CSS to our rig in case botstrap gets depreciated or we stop using it. (Note: I tried adding the CSS for `sr-only` in main.scss but that didn't work)
- Add a warning that appears if `AltText` is empty or missing in the google doc

*[See PR here](https://github.com/reuters-graphics/bluprint_graphics-kit/pull/51)*

### In the master google doc:
- Add a note to editors that explains what AltText is and how it should be edited at the top of the google doc
- Add props for `AltText` and `ariaHidden` for the ai2svelte block in the master google doc

*See suggestions in red in [this dummy google doc](https://docs.google.com/document/d/1yyXpx-Cqycj2vJAi-aa3saT1bWO-V9zQsy-OeF2ej7M/edit)*

## References for best practices
Read about `aria-hidden` [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden):

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. This can improve the experience for assistive technology users by hiding purely decorative content, such as icons or images, etc...
       
Semantic html is recommended as part of [best practices](http://web-accessibility.carnegiemuseums.org/foundations/semantic/#:~:text=Structural%2C%20semantic%20HTML%20is%20the,read%20by%20a%20screen%20reader.).

**Comment by hobbes7878** [comment]
Thanks for this @MinamiFunakoshiTR! Have a couple thoughts on the code details, but my first question is do we have any resources that talk about best practice for handling aria-only (i.e., the inverse of aria-hidden) content on the page?

Basically looking for a source on where [this CSS came](https://github.com/reuters-graphics/bluprint_graphics-kit/pull/51/files#diff-8f2d13ab472d927ae2e6eeb18cfa7aeedb5582a6aa6fba2731697f14d42d16cdR128-R138) and whether we're sure that's best practice.

**Comment by hobbes7878** [comment]
Quick google got me a couple different versions. Bootstrap 5 introduced a [`.visually-hidden` class](https://github.com/twbs/bootstrap/blob/1df098361cac04217d6a464c80e890c4335ecb5c/scss/mixins/_visually-hidden.scss#L8), which looks like yours, but with important tags, which in this case I think is a good use.

But for a global rule like this, I think the better thing would be to add it to our main [SCSS library](https://github.com/reuters-graphics/style/tree/master/packages/main/scss) so it can apply across our projects. I can take that on as part of this PR, and I kinda like the idea of having some accessibility relative SCSS mixins we can document as well as the overriding class, like what Bootstrap 5 has done.

**Comment by hobbes7878** [comment]
OK, couple other things I'll suggest at a high-level, and then I think we can deal with small naming conventions and things in the PR:

Generally, I don't think this PR should add any SCSS to the kit's global or main.scss styles. I do like the idea I mentioned of adding bs5's `.visually-hidden` class to our main style lib, but we can also duplicate that rule locally-scoped within the `Ai2svelte` component if that gets this change out more quickly.

I also think we should use [console.warn](https://developer.mozilla.org/en-US/docs/Web/API/console/warn) for missing aria attributes and accessibility issues generally. That lines up with what Svelte is already doing to warn us about a11y issues _it_ finds, and I think the training for the team should be to clear those out. There are also some valid cases for ai2svelte that don't require aria description, _I think_, like when we use AI to make a purely decorative part of a page, that as currently written would look like errors.

One way to trigger that console warning within the `Ai2Svelte` component would be to check for agreement between ariaHidden prop and the aria description passed in. If it's set hidden but no description or a blank is given, we can then warn.

As I'm looking at it now, I'm not sure srDescription/ariaDescripton should be a slot. We're not hiding the title and chatter, which are external to AI anyway, so I don't really see the use case for making additional heading tags in markdown. I think we just want to pass in a string, no? I would be interested to know if there's a compelling reason to split that description into multiple paragraph tags, or if just one would do us, in which case, I think you just make that a string prop and wrap it in p's. But would love to see an example of screenreader-only description for a graphic with more complex structure to wrap my head around.

I'm not sure aria-hidden should necessarily be default true. I think hiding text from screen readers is something we always want to do intentionally. I'd set that false.

**Comment by juruwolfe** [comment]
Just weighing in on that last point (default to true vs fault for hidden) because it's something we discussed. 

As it stands, SRs will read every label in an ai2html chart which comes out like gibberish. Happy to make a recording for you if you're curious, but it just sounds like random unrelated words strung together as a sentence. @pkd2512 is thinking through cases where we might actually want the text to be read, but I think those will be exceptionally rare. I worry that leaving it as something we have to manually turn off will mean a lot get missed and I suspect in 90%+ cases we're not going to want an ai2html chart read aloud as is.

**Comment by hobbes7878** [comment]
Yeah, OK. I can see that balance. Would just want to make that _very_ clear in the component docs for `Ai2svelte` that we've coded in a difference between what you're seeing and what a screen reader will read by default. So maybe @MinamiFunakoshiTR can add a shouty line in the docs page for that, then! 👍

**Comment by MinamiFunakoshiTR** [comment]
Re: the srDescription getting markdown -- I proposed this because I know sometimes people in Asia/EMEA put the title and description inside the ai file instead of putting it on the google doc. I think it's partly to style the deck as they like, and partly out of habit.

If the chart title and description are all inside the .ai file, and we're rewriting it in srDescription, it would be nice to add some hierarchy to it. But I also get the argument that people should be writing chart title/description in the google doc anyway, not in the ai.

If we're going to get people to write the chart title/description in the google doc, I think it's fine to just pass a string. If we are going to have cases where we rehash the title/description in srDescription, though, I think adding markdown would be nice.

**Comment by MinamiFunakoshiTR** [comment]
Hi! Looping back on this with a list of what I think we've decided on doing. Please let me know if I've missed or misunderstood something. If the list looks good, I'll make the changes and do a new PR.

@hobbes7878  will:
- Add `.visually-hidden` class to our main [SCSS library](https://github.com/reuters-graphics/style/tree/master/packages/main/scss)

@MinamiFunakoshiTR will:
- Add `.visually-hidden` class to the altText
- Take out the `.sr-only` CSS from the graphics-kit bluprint
- Use [console.warn](https://developer.mozilla.org/en-US/docs/Web/API/console/warn) for missing alt text, which is triggered when `ariaHidden = true` but alt text is missing or blank
- Set `ariaHidden = true` by default. Explain clearly in the google doc that this can be set to `false` to make screen readers read aloud the html
- Rename `srDescription`  as `areaDescription` 
- Turn the `srDescription` slot into a default, unnamed slot that takes a string

@hobbes7878  -- I'm not sure how you're suggesting we add a data table using the `areaDescription` prop. I think we should make it as easy as possible to add data tables so we would do this more often.

**Comment by MinamiFunakoshiTR** [comment]
## What's new
- Made edits to Page.svelte in the bluprint graphics kit. See PR [here](https://github.com/reuters-graphics/bluprint_graphics-kit/pull/51) 
- Made edits to the [dummy google doc](https://docs.google.com/document/d/1yyXpx-Cqycj2vJAi-aa3saT1bWO-V9zQsy-OeF2ej7M/edit)

## Next steps
- Merge all PRs
- Update the master google doc

@hobbes7878  let me know if you want me to update the master google doc once you've had a chance to look at all the final edits. Thanks!

**Comment by hobbes7878** [comment]
This is now published as `0.2.0`. PR was merged in the kit in https://github.com/reuters-graphics/bluprint_graphics-kit/pull/51 and bumped components to the new version in its deps.

Leave it to @MinamiFunakoshiTR to update the master Google doc for kit.

Thanks, y'all for doing this. I'll close this issue out.
