### ISSUE TITLE
stackBackground is always true

### ISSUE THREAD

**Issue by man-shar** [reuters-graphics/graphics-svelte-components#35]
Had this issue recently in a graphic.
stackBackground comes in as a string from google docs, hence always resolves to true in the conditions [here](https://github.com/reuters-graphics/graphics-svelte-components/blob/master/src/lib/Scroller/Background.svelte#L13-L14)

I've added a terrible looking condition here: #34 

There are other ways to fix this, though:

1. Could edit condition in Page.svelte when passing the prop.
2. Could change it to a number right after we fetch google docs, before writing to content.json

Let me know what you folks think!

**Comment by hobbes7878** [comment]
Closed in https://github.com/reuters-graphics/bluprint_graphics-kit/commit/f9cd98a980967188f1bec14a184a416dca0ce38b
