### ISSUE TITLE
Path issue with dynamic import in the ai2svelte component

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/graphics-svelte-components#4]
I get this error when I tried to use the component in the boilerplate rig project.

![Screenshot 2021-09-29 at 4 04 43 PM](https://user-images.githubusercontent.com/62298563/135348260-ce1c4f70-33ee-491e-9dde-64c5c9634823.png)

**Comment by hobbes7878** [comment]
Take a screenshot of your `src/` directory for me. Should be something like:

```
src/
  lib/
    ai2html/
      ai-chart.svelte
    Page.svelte
```

If so, we may be screwed, b/c the path is searching from `./ai2html` _inside_ node_modules where the component is.

**Comment by MinamiFunakoshiTR** [comment]
This is what it looks like in my boilerplate project. It does seem like the path is searching for ./ai2html inside node_modules

![Screenshot 2021-09-29 at 5 12 42 PM](https://user-images.githubusercontent.com/62298563/135355906-88422bd6-4ae8-49a6-91f3-b419602ef691.png)

**Comment by hobbes7878** [comment]
Yeah, more I look at the rules, I think that's exactly what's happening. 

This is now relative to `node_modules` not our `src/lib`:

```javascript
Ai2svelteGraphic = (await import(`./ai2html/${componentName}.svelte`)).default;
```

... so what if we did this instead:

We basically can't package this component in our components lib b/c of that pathing blocker. _Instead_ let's put it directly in our ai2html directory with the example components. This is going to apply to a scrolly version, too, so we'd end up with something like this:

```bash
src/
  lib/
    ai2html/
      ai-chart.svelte
      ai-scroller-chart-1.svelte
      ai-scroller-chart-2.svelte
      ai-scroller-chart-3.svelte
      Ai2svelte.svelte # 👈
      Ai2svelteScroller.svelte # 👈
```

And then our dynamic imports will look like this within those components:

```javascript
Ai2svelteGraphic = (await import(`./${componentName}.svelte`)).default;
```

**Comment by MinamiFunakoshiTR** [comment]
Sounds good. will add the component back to the boilerplate and delete it from this repo.
fyi, onMount is unnecessary for dynamic loading (I thought it was), so I'll nix onMount too, unless you think otherwise. Taking out onMount makes the graphic load a little faster.

**Comment by hobbes7878** [comment]
Closing this in favour of the Ai2svelte and Scroller components added in https://github.com/reuters-graphics/graphics-svelte-components/commit/283294fef7f1c3903d9c4c789b0ddb9524bac6da
