### ISSUE TITLE
Code snippet in documentation different from pre-baked code in kit

### ISSUE THREAD

**Issue by allyjlevine** [reuters-graphics/graphics-svelte-components#40]
It looks to me like the svelte code snippet for the ai2html scroller is different from what comes pre-baked into Page.svelte when you start up a new bluprint. For example, the main function in the [component documentation](https://reuters-graphics.github.io/graphics-svelte-components/components/scroller) is called `makeSteps` but the function in `Page.svelte` is `makeScrollerSteps`.

Let me know if I'm just reading all of this wrong and not using the docs correctly!

**Comment by hobbes7878** [comment]
Think we got this.
