### ISSUE TITLE
Remove dynamic importing examples from docs

### ISSUE THREAD

**Issue by fcage** [reuters-graphics/graphics-svelte-components#57]
The AI scroller component does some dynamic loading. Because of this, if it's the item at the top of the page (ie right under the headline) there's some obvious page jumping around business going on here when coming to the page. Are there ways we can fix this? Here are two ideas

- give the containing div a min height of 100vh, since in theory a scroller will be at least 100vh or we wouldn't be using it for this purpose
- OR, bake out the steps and the shell html of the scroller and and load the ai components in the background? Is there a way we can more optimally use slots in this case?

**Comment by hobbes7878** [comment]
Quick Q on this @fcage, but are y'all using dynamic imports using strings from a gdoc that represent components? I'm very keen to basically declare that an anti-pattern for us b/c it _always_ makes for these loading issues. The Scroller component itself assumes components are passed to it, not strings, but I do realise the example in the docs uses this anti-pattern with the Svelte await tags thingy..

If you _are_ already using components, then is the `preload` prop not getting the job done? In cases like top of the page, I'd be inclined to disable it by setting to `0`.

**Comment by fcage** [comment]
Honestly havent had time to look. We were using the default setup as it's presented in the App.svelte file. You'll see my hack below to set min height. 

  {:else if block.Type === 'ai-scroller'}
      {#await makeScrollerSteps(block.steps)}
        <div style="min-height: 100vh;"></div>
      {:then steps}
        <Scroller
          steps="{steps}"
          backgroundSize="{block.BackgroundSize}"
          foregroundPosition="{block.ForegroundPosition}"
          id="{block.ID}"
          embedded="{embedded}"
          stackBackground="{false}"
        />
      {:catch error}
        {console.error('Error making steps for scroller', error)}
      {/await}
    {:else}

**Comment by hobbes7878** [comment]
This is done in new repo: https://reuters-graphics.github.io/graphics-components/?path=/docs/components-scroller--default
